-- create database assignment3;
CREATE TABLE DEPARTMENT(DEPT_ID INT PRIMARY KEY, DEPT_NAME VARCHAR(50));
CREATE TABLE EMPLOYEE (EMP_ID INT PRIMARY KEY,EMP_NAME VARCHAR(20), DEPT_ID INT, SALARY INT4, MANAGER INT,CONSTRAINT FK_KEY FOREIGN KEY(DEPT_ID) REFERENCES DEPARTMENT(DEPT_ID));
INSERT INTO DEPARTMENT VALUES(1,'FINANCE'),
(2,'TRAINING'),
(3,'MARKETING');
INSERT INTO EMPLOYEE VALUES(1,'ARUN',1,8000,4),
(2,'KIRAN',1,7000,1),
(3,'SCOTT',1,3000,1),
(4,'MAX',2,9000,NULL),
(5,'JACK',2,8000,4),
(6,'KING',NULL,6000,1);
---------- (ORDER BY)---------------
USE ASSIGNMENT2;
SELECT * FROM AUTHORS ORDER BY ANAME ASC;
SELECT * FROM PUBLISHERS  ORDER BY PNAME DESC;

---------- (GROUP BY)---------------
USE ASSIGNMENT3;
SELECT *,SUM(SALARY) FROM EMPLOYEE GROUP BY DEPT_ID;
SELECT DEPT_ID, SUM(SALARY) AS SAL FROM EMPLOYEE WHERE SALARY > 17000 GROUP BY DEPT_ID;

---------- (HAVING)---------------
SELECT DEPT_ID, SUM(SALARY) FROM EMPLOYEE GROUP BY DEPT_ID HAVING sum(SALARY) >18000;
SELECT DEPT_ID, SUM(SALARY) FROM EMPLOYEE GROUP BY DEPT_ID HAVING sum(SALARY) <20000;